<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ZaDataStudio.Application\ZaDataStudio.Application.csproj" />
    <ProjectReference Include="..\ZaDataStudio.Infrastructure\ZaDataStudio.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="5.2.2" />
    <PackageReference Include="ClosedXML" Version="0.104.2" />
  </ItemGroup>


</Project>